version: "3.9"
services:
  primary:
    image: alejandrodu/mariadb-primary

  replica1:
    image: alejandrodu/mariadb-replica
    depends_on:
      - mariadb-primary
    environment:
      MARIADB_PRIMARY_HOST: primary
      MARIADB_PRIMARY_PORT: 3306

  replica2:
    image: alejandrodu/mariadb-replica
    depends_on:
      - mariadb-primary
    environment:
      MARIADB_PRIMARY_HOST: primary
      MARIADB_PRIMARY_PORT: 3306

  maxscale:
    image: alejandrodu/mariadb-maxscale
    command: --admin_host 0.0.0.0 --admin_secure_gui false
    depends_on:
      - primary
      - replica1
      - replica2
    ports:
      - 4000:4000
      - 8989:8989
      - 27017:27017
