version: "3.9"
services:
  primary:
    image: 192.168.1.200:5000/alejandrodu/mariadb-arm-primary
    ports:
    - "3306:3306"

  replica:
    image: 192.168.1.200:5000/alejandrodu/mariadb-arm-replica
    environment:
      PRIMARY_SERVER_IP_ADDRESS: primary
    ports:
    - "3307:3306"
    deploy:
      replicas: 2
    depends_on:
      - primary

  visualizer:
    image: alexellis2/visualizer-arm
    ports:
      - 9000:8080
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role==manager"
