version: "3.9"
services:
  primary:
    image: 192.168.1.200:5000/alejandrodu/mariadb-arm-primary

  replica:
    image: 192.168.1.200:5000/alejandrodu/mariadb-arm-replica
    deploy:
      replicas: 2
    depends_on:
      - primary
