version: "3.9"
services:
  primary:
    image: alejandrodu/mariadb-primary

  replica:
    image: alejandrodu/mariadb-replica
    deploy:
      replicas: 2
    depends_on:
      - mariadb-primary
    environment:
      MARIADB_PRIMARY_HOST: primary
  
  maxscale:
    image: alejandrodu/mariadb-maxscale
    command: --admin_host 0.0.0.0 --admin_secure_gui false
    ports:
      - 4000:4000
      - 8989:8989
      - 27017:27017
